#!/usr/bin/env bash
#
# Provision the single-node Garage dev stack for the asset-store backend spike
# (S-001/S-004): apply a one-node layout, create the four category buckets,
# create an access key, grant it ownership, and write deploy/compose/.env.garage
# with S3 credentials for the test suite.
#
# Idempotent: safe to re-run. Requires the stack to be up:
#   docker compose -f docker-compose.garage.yml up -d
set -euo pipefail

CONTAINER="asset-store-garage"
KEY_NAME="asset-store-dev"
# Fixed DEV-ONLY credentials so the test suite is reproducible across re-provisions.
# Garage key names are not unique, so we import a known key id/secret rather than
# `key create` (which would silently make duplicates on every run).
ACCESS_KEY="GKa55e70000000000000000001"
SECRET_KEY="c5366f706591234709384b7eb634827a11c1a7b5945a86941d62135e80c8da7c"
BUCKETS=(cache tmp users results)
ENV_FILE="$(cd "$(dirname "$0")" && pwd)/.env.garage"

g() { docker exec "$CONTAINER" /garage "$@"; }

# Wait for the RPC API to answer.
for _ in $(seq 1 30); do
  if g status >/dev/null 2>&1; then break; fi
  sleep 1
done

# Apply a single-node layout only if this node has no role yet.
if g status 2>/dev/null | grep -q 'NO ROLE ASSIGNED'; then
  node_id="$(g node id -q | cut -d@ -f1)"
  g layout assign -z dc1 -c 1G "$node_id"
  g layout apply --version 1
fi

# Buckets (create + grant are both idempotent).
for b in "${BUCKETS[@]}"; do
  g bucket create "$b" >/dev/null 2>&1 || true
done

# Access key: import the fixed dev key if it is not already present.
if ! g key list 2>/dev/null | grep -q "$ACCESS_KEY"; then
  g key import "$ACCESS_KEY" "$SECRET_KEY" --yes -n "$KEY_NAME" >/dev/null
fi

for b in "${BUCKETS[@]}"; do
  g bucket allow --read --write --owner "$b" --key "$ACCESS_KEY" >/dev/null
done

cat > "$ENV_FILE" <<EOF
# Generated by garage-init.sh — DEV ONLY, do not commit.
ASSET_STORE_S3_ENDPOINT=http://127.0.0.1:3900
ASSET_STORE_S3_REGION=garage
ASSET_STORE_S3_ACCESS_KEY=$ACCESS_KEY
ASSET_STORE_S3_SECRET_KEY=$SECRET_KEY
EOF

echo "Provisioned Garage. Wrote $ENV_FILE"
echo "  buckets: ${BUCKETS[*]}"
echo "  access key: $ACCESS_KEY"
